### ISSUE TITLE
Tetimonials 

### ISSUE THREAD

**Issue by Mammarrazzi** [Mammarrazzi/website#25]
1. Testimonials are too long. Doesn't show the full content on the website.
2. Also need to update two new profile photos for testimonials.

**Comment by uicomponent** [comment]
Please send me these avatars

**Comment by Mammarrazzi** [comment]
I sent you from my hotmail. I can send it to you again if you need.

**Comment by uicomponent** [comment]
2. Photos are fixed. Without watermark now.
1. Testimonials should not be too big by default website design. I recommend not to change it, because after sliding testimonials sliders (photographers) it will be different height of each testimonial and page will have "jump" effect during auto-sliding. Full testimonial text is possible to see when click at photographer name.

**Comment by Mammarrazzi** [comment]
That's great!
