### ISSUE TITLE
Photographers can not change their profile pictures

### ISSUE THREAD

**Issue by Mammarrazzi** [Mammarrazzi/website#37]
Photographers can not change their profile pictures right now. We should give them options to change their profile pictures.

In addition, they should also be able to change their phone number, address, city, state and zip code.

**Comment by manadream** [comment]
@Mammarrazzi This has been completed. Can you verify and close this ticket if it is satisfactory?

**Comment by manadream** [comment]
@Mammarrazzi Sorry, only the photo upload part has been completed. I will address the other parts of this ticket later. Either way, can you try out the photo upload?

**Comment by Mammarrazzi** [comment]
Ok. I tested the profile picture. It works! I wonder if there is a way we can reinforce that the picture needs to be square. We need to do that on the application too.

**Comment by uicomponent** [comment]
We have it in application already. The same code can be copied into profile.

**Comment by manadream** [comment]
@ilinyevg There is existing code that resizes the image to have a max size of 200 x 200, which I have already included in with this change, but this does not enforce the image to be square, it just resizes the photo so that it has a maximum side length of 200px, but doesn't change the aspect ratio. I uploaded a rectangular image and it resized it to 200px X 133px. To fix this, I added the crop parameter to the resize method, so it looks like this `$image->resize( 200, 200, array('center', 'center'));`. This forces the photo to be square and crops it to force the square aspect ratio. What we should do on the future is add some sort of cropping tool so that the user can select a region of the photo to use and force that region to be square.

**Comment by manadream** [comment]
@Mammarrazzi can you try it now? It should force the avatar to be square.

**Comment by Mammarrazzi** [comment]
Well done! I tested both application and updating profile picture. They both work!

**Comment by Mammarrazzi** [comment]
I notice that photographers can edit Address, City, State, Zip code 	and Phone information now. However, there is not save button. Can you add a save or update button. When I log out, the information didn't save.

**Comment by manadream** [comment]
I have not completed the functionality to update the contact info, I'm working on that now

**Comment by Mammarrazzi** [comment]
Got you. While you are working on that. Can we make sample photos editable as well?

**Comment by manadream** [comment]
That should be another ticket, it's more work. Really any change or set of changes should be in an individual ticket so that tickets don't just keep getting bigger.

**Comment by manadream** [comment]
@Mammarrazzi I've added the ability to save changes to the user info. Can you test it out? It still needs some more work on validating the user input, but it works for now.

**Comment by Mammarrazzi** [comment]
Got you. It works! Ok. Let's not worry about changing sample photos for now. It's not as important. I'll go ahead and close this issue then.
